/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sia;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import sia.connect;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.table.TableModel;


/**
 *
 * @author Dewi
 */
public class Input_Data_Nilai extends javax.swing.JFrame {

    /**
     * Creates new form Input_Data_Nilai
     */
    public Input_Data_Nilai() {
        initComponents();
        siswa2();
        mapel();
        jComboBox4.setSelectedItem("");
       jComboBox3.setSelectedItem("");
      
    }
    
    public void BersihData(){
        jComboBox1.getSelectedItem().toString();
        jComboBox3.getSelectedItem().toString();
        jComboBox4.getSelectedItem().toString();
        
        }
    public void mapel(){
       DefaultTableModel tbl=new DefaultTableModel();
    tbl.addColumn("Kode Matapelajaran");
    tbl.addColumn("Matapelajaran");
    tbl.addColumn("Nilai");

    jTable1.setModel(tbl);
    try{
      Statement statement= (Statement) connect.GetConnection().createStatement();
      ResultSet res=statement.executeQuery("select * from mapel where kode_kelas ='"+jComboBox1.getSelectedItem()+"'");
      jTable1.removeAll();
      while(res.next())
      {
          tbl.addRow(new Object[]{
          res.getString("kode_mapel"),
          res.getString("nama")
          
      });
          jTable1.setModel(tbl);
      }
          
      }catch (Exception e){
          JOptionPane.showMessageDialog(rootPane, "Salah");
      }
        
    }
          
      
       public void siswa2(){
           try{
        Statement statement= (Statement) connect.GetConnection().createStatement();  
        ResultSet res=statement.executeQuery("select * from kelas ");
        while (res.next()){
           
            jComboBox1.addItem(res.getString("kode_kelas"));
                       
        }
        }catch(Exception t){
            JOptionPane.showMessageDialog(rootPane, "Salah");
        }
      }
    public void siswa(){
           try{
        Statement statement= (Statement) connect.GetConnection().createStatement();  
        ResultSet res=statement.executeQuery("select * from siswa where nis = '"+jComboBox3.getSelectedItem()+"'");
        jComboBox4.removeAllItems();
        while (res.next()){
           jComboBox4.addItem(res.getString("nama"));
    }
        }catch(Exception t){
            JOptionPane.showMessageDialog(rootPane, "Salah");
        }
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Input Data Nilai");

        jLabel2.setText("Kelas");

        jLabel3.setText("NIS");

        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });

        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("NEW");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("EDIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setText("Nama");

        jButton5.setText("HOME");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton1)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2)
                        .addGap(30, 30, 30)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(39, 39, 39)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, 98, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(183, 183, 183))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        String A=jComboBox1.getSelectedItem().toString();
        String B=jComboBox3.getSelectedItem().toString();
        String C=jComboBox4.getSelectedItem().toString();
        String D=jTable1.getValueAt(0,3).toString();
         String E=jTable1.getValueAt(1, 3).toString();
         String F=jTable1.getValueAt(2,3).toString();
          String G=jTable1.getValueAt(3,3).toString();
           String H=jTable1.getValueAt(4,3).toString();
            String I=jTable1.getValueAt(5,3).toString();
            String J=jTable1.getValueAt(6,3).toString();
             String K=jTable1.getValueAt(7,3).toString();
             
              
                if ((A.isEmpty()) | (B.isEmpty()) |(C.isEmpty()))
            {JOptionPane.showMessageDialog(null,"data tidak boleh kosong, silahkan dilengkapi");
            jComboBox1.requestFocus();
        }else {
            try {
              Statement statement= (Statement) connect.GetConnection().createStatement();
              statement.executeUpdate("Update nilai set nis='"+B+"',"+"nama='"+C+"',"+D+"',"+E+"',"+F+"',"+G+"',"+H+"',"+I+"',"+J+"',"+K+"Where kelas='"+A+"'");
              statement.close();
              JOptionPane.showMessageDialog(null, "berhasil diedit");
            }
            catch(Exception t){
                 JOptionPane.showMessageDialog(null, "gagal diedit");
            }
       
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String A=jComboBox1.getSelectedItem().toString();
        String B=jComboBox3.getSelectedItem().toString();
        String C=jComboBox4.getSelectedItem().toString();
        int Rows =jTable1.getRowCount();
        int sum=0;
        for (int x=0; x<Rows; x++){
            String nilai = jTable1.getValueAt(x, 2).toString();
            int nilai1 = Integer.parseInt(nilai);
            sum = sum + nilai1;
            
        }
        int sum1 = sum/8;
        
        
             
      
               
        
        if ((A.isEmpty()) | (B.isEmpty()) |(C.isEmpty()))
            {JOptionPane.showMessageDialog(null,"data tidak boleh kosong, silahkan dilengkapi");
            }else {
            try {
              Statement statement= (Statement) connect.GetConnection().createStatement();
              statement.executeUpdate("insert into nilai VALUES('"+B+"','"+C+"','"+jTable1.getValueAt(0,2)+"','"+jTable1.getValueAt(1,2)+"','"+jTable1.getValueAt(2,2)+"','"+jTable1.getValueAt(3,2)+"','"+jTable1.getValueAt(4,2)+"','"+jTable1.getValueAt(5,2)+"','"+jTable1.getValueAt(6,2)+"','"+jTable1.getValueAt(7,2)+"','"+sum1+"','"+A+"');");
              statement.close();
              JOptionPane.showMessageDialog(null, "berhasil disimpan");
            }
            catch(Exception t){
               JOptionPane.showMessageDialog(null, t.getMessage());  
            }
           
            BersihData();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        BersihData();
        jComboBox1.requestFocus();
        jButton2.setEnabled(true);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       String A=jComboBox1.getSelectedItem().toString();
         try {
              Statement statement= (Statement) connect.GetConnection().createStatement();
              statement.executeUpdate("DELETE from nilai where kelas=('"+A+"');");
              JOptionPane.showMessageDialog(null, "berhasil dihapus");
                BersihData();
                jComboBox1.requestFocus();
                
            }
            catch(Exception t){
                 JOptionPane.showMessageDialog(null, "gagal dihapus");
            
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        try{
        Statement statement= (Statement) connect.GetConnection().createStatement();  
        ResultSet res=statement.executeQuery("select * from siswa where kelas = '"+jComboBox1.getSelectedItem()+"'");
         jComboBox3.removeAllItems();
         jComboBox4.removeAllItems();
        while (res.next()){
           jComboBox4.addItem(res.getString("nama"));
            jComboBox3.addItem(res.getString("nis"));
            
            
        }
        }catch(Exception t){
            JOptionPane.showMessageDialog(rootPane, "Salah");
        }
        mapel();
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        // TODO add your handling code here:
        siswa();
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input_Data_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input_Data_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input_Data_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input_Data_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input_Data_Nilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
